import genShopItem from 'utils/genShopItem';

export default {
  name: 'DaVinciAndThe7CounterfeitHeroicSpirits',
  drops: [
    {
      id: 'Drop.real.manuscript',
      type: 'ADD',
      min: 0,
      max: 24,
      step: 1,
    },
    {
      id: 'Drop.fake.manuscript',
      type: 'ADD',
      min: 0,
      max: 24,
      step: 1,
    },
    {
      id: 'Drop.mona.lisa.fake',
      type: 'ADD',
      min: 0,
      max: 12,
      step: 1,
    },
    {
      id: 'Drop.self.portrait',
      type: 'ADD',
      min: 0,
      max: 12,
      step: 1,
    },
    {
      id: 'Drop.vitruvian.man.fake',
      type: 'ADD',
      min: 0,
      max: 12,
      step: 1,
    },
  ],
  quests: [],
  shop: [
    genShopItem(
      'Event.real.box',
      'Drop.real.manuscript',
      6,
      600,
    ),
    genShopItem(
      'Event.fake.box',
      'Drop.fake.manuscript',
      6,
      600,
    ),
    genShopItem(
      'Ce.school.of.chaldea',
      'Drop.mona.lisa.fake',
      2,
      200,
    ),
    genShopItem(
      'Asc.heart.of.a.foreign.god',
      'Drop.mona.lisa.fake',
      20,
      30,
    ),
    genShopItem(
      'Asc.spirit.root',
      'Drop.mona.lisa.fake',
      20,
      30,
    ),
    genShopItem(
      'Asc.bloodstone.tear',
      'Drop.mona.lisa.fake',
      20,
      20,
    ),
    genShopItem(
      'Asc.secret.gem.of.swords',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.secret.gem.of.bows',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.secret.gem.of.lances',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.secret.gem.of.cavalry',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.secret.gem.of.spells',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.secret.gem.of.killing',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.secret.gem.of.madness',
      'Drop.mona.lisa.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.mana.prism',
      'Drop.mona.lisa.fake',
      500,
      1,
    ),
    genShopItem(
      'Ce.school.of.chaldea',
      'Drop.self.portrait',
      1,
      200,
    ),
    genShopItem(
      'Asc.black.tallow',
      'Drop.self.portrait',
      20,
      40,
    ),
    genShopItem(
      'Asc.talon.of.chaos',
      'Drop.self.portrait',
      20,
      30,
    ),
    genShopItem(
      'Asc.phoenix.plume',
      'Drop.self.portrait',
      20,
      20,
    ),
    genShopItem(
      'Asc.magic.gem.of.swords',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Asc.magic.gem.of.bows',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Asc.magic.gem.of.lances',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Asc.magic.gem.of.cavalry',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Asc.magic.gem.of.spells',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Asc.magic.gem.of.killing',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Asc.magic.gem.of.madness',
      'Drop.self.portrait',
      20,
      10,
    ),
    genShopItem(
      'Ce.school.of.chaldea',
      'Drop.vitruvian.man.fake',
      1,
      200,
    ),
    genShopItem(
      'Asc.warhorses.immature.horn',
      'Drop.vitruvian.man.fake',
      20,
      40,
    ),
    genShopItem(
      'Asc.ghost.lantern',
      'Drop.vitruvian.man.fake',
      20,
      20,
    ),
    genShopItem(
      'Asc.homunculus.baby',
      'Drop.vitruvian.man.fake',
      20,
      20,
    ),
    genShopItem(
      'Asc.shinning.gem.of.swords',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.shinning.gem.of.bows',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.shinning.gem.of.lances',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.shinning.gem.of.cavalry',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.shinning.gem.of.spells',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.shinning.gem.of.killing',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.shinning.gem.of.madness',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.fou.kun.of.the.star',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
    genShopItem(
      'Asc.fou.kun.of.the.sun',
      'Drop.vitruvian.man.fake',
      20,
      10,
    ),
  ],
  getRequired: () => ({
    drops: [],
    quests: [],
    ap: 0,
  }),
};
